swiftlint_version: 0.24.0
disabled_rules: 
- attributes
- closure_end_indentation
- nesting
- number_separator
- unused_closure_parameter
- vertical_parameter_alignment
- shorthand_operator
- identifier_name
opt_in_rules:
- closure_parameter_position
- closure_spacing
- conditional_returns_on_newline
- contains_over_first_not_nil
- cyclomatic_complexity
- empty_count
- explicit_init
- fatal_error_message
- first_where
- force_unwrapping
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- literal_expression_end_indentation
- object_literal
- operator_usage_whitespace
- overridden_super_call
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- sorted_first_last
- sorted_imports
- strict_fileprivate
- switch_case_on_newline
- unneeded_parentheses_in_closure_argument
excluded: 
- Pods
- SherpanyChallenge/Resources
- Playground.playground
force_cast: warning # implicitly
function_body_length:
  warning: 100
  error: 250
type_body_length: 
- 500 
- 1000
file_length:
- 500
- 1200
line_length:
- 200
- 300
cyclomatic_complexity:
        ignores_case_statements: true
