//
//  Log.swift
//  SherpanyChallenge
//
//  Created by Mikolaj Kalinowski on 06/01/2018.
//  Copyright © 2018 Higher Order. All rights reserved.
//

import Foundation
import os

func log(_ message: CustomStringConvertible,
         type: OSLogType = .debug,
         filename: String = #file,
         line: Int = #line,
         function: String = #function) {
    print("\((filename as NSString).lastPathComponent):\(line) \(function):\r\(message)\n")
}

/*
Did something go wrong that was beyond our control?
+ Yes: Was the issue generated by the system outside the app?
    + Yes: .fault
    - No: .error
- No: Is this information only useful in crash reports?
    + Yes: .info
    - No: Is this noisy information that we only occassionally want to turn on during development?
        + Yes: .debug
        - No: .default
*/
